# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-security:
        applies-to: security-updates
        patterns:
          - "*"
      actions-major:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"
      actions-minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "docker"
    cooldown:
      default-days: 7
    directories:
      - "/testing"
    schedule:
      interval: "weekly"
    groups:
      docker-security:
        applies-to: security-updates
        patterns:
          - "*"
      docker-major:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"
      docker-minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    cooldown:
      default-days: 7
    directories:
      - "/testing"
    schedule:
      interval: "weekly"
    groups:
      docker-compose-security:
        applies-to: security-updates
        patterns:
          - "*"
      docker-compose-major:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"
      docker-compose-minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gomod-security:
        applies-to: security-updates
        patterns:
          - "*"
      gomod-major:
        applies-to: version-updates
        update-types:
          - "major"
        patterns:
          - "*"
      gomod-minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
