name: Build

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: LouisBrunner/.github/.github/workflows/lint-go.yml@main
    with:
      run: go test -v ./...

  cross-build:
    name: Cross-compile
    runs-on: ubuntu-24.04
    needs: test
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        include:
          - label: armv5
            arch: arm
            arm: 5
          - label: armv6
            arch: arm
            arm: 6
          - label: armv7
            arch: arm
            arm: 7
          - label: arm64
            arch: arm64
          - label: amd64
            arch: amd64
          - label: i386
            arch: 386
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v ./...
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.arm }}

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: avahi2dns-linux-${{ matrix.label }}
          path: avahi2dns
