# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  release:
    types: [created]

permissions: {}

jobs:
  release:
    name: Upload binaries
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download all workflow artifacts
        uses: dawidd6/action-download-artifact@b6e2e70617bc3265edd6dab6c906732b2f1ae151 # v21
        with:
          workflow: build.yml
          branch: ${{ github.event.release.target_commitish }}

      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          for arch in armv5 armv6 armv7 arm64 amd64 i386; do
            gh release upload "$TAG" "avahi2dns-linux-${arch}/avahi2dns#avahi2dns-linux-${arch}"
          done
